### ISSUE TITLE
Add a mock clock

### ISSUE THREAD

**Issue by schomatis** [libp2p/go-flow-metrics#17]
Context: https://github.com/libp2p/go-libp2p-core/issues/267

It seems all `Meter`s use a single `globalSweeper` running on the Go clock. I'm not sure how to go about this. For example:

* Should each `Meter` have its own `sweeper` now (with its own mock/Go clock)?
* Should we still rely on the  `globalSweeper` but somehow have it track individual clocks (either in another structure like `meters       []*Meter` or inside the `Meter`s themselves)?

@Stebalien help (cc @marten-seemann)

**Comment by Stebalien** [comment]
So, I created this library because metrics kept showing up in performance profiles.

- Each meter should not have a sweeper, that would kill performance.
- We can't have individual clocks (performance, complexity, size).

The best we could do would be to have a global clock and mock it via an environment variable (on init).

**Comment by marten-seemann** [comment]
> The best we could do would be to have a global clock and mock it via an environment variable (on init).

Not sure how you'd inject a clock via an environment variable, the caller needs to be able to control the (mock) clock.

We could introduce a `SetClock(clock)` function.

The interesting thing here is that once a `sweeper` is started, it can't be stopped. That means we can only single mock clock for all test cases. I don't expect this to be a problem though, after all, the tests work right now using a single clock.

**Comment by Stebalien** [comment]
> Not sure how you'd inject a clock via an environment variable, the caller needs to be able to control the (mock) clock.

Uh, sorry, not environment variable. Global variable.

> We could introduce a SetClock(clock) function.

That also works, but it would likely still be a global.

**Comment by schomatis** [comment]
Thanks for the input. I'm going then (unless someone says otherwise) with the global `SetClock` API meant to be called only once and _before_ registering (using) any meter (leveraging the `sweepOnce` mechanism). It's on the test to inject the mock clock before using meters. (I'm assuming that separate tests have separate global/static contexts and hence separate sweepers.)

**Comment by schomatis** [comment]
https://github.com/libp2p/go-flow-metrics/pull/18

**Comment by schomatis** [comment]
> (I'm assuming that separate tests have separate global/static contexts and hence separate sweepers.)

@marten-seemann @Stebalien We're sharing the global sweeper across tests so the above isn't correct and I'll need some advice on how to proceed.
