### ISSUE TITLE
Refresh README 

### ISSUE THREAD

**Issue by Hellseher** [libp2p/go-flow-metrics#30]
Hi,

I came here during packages upgrade task in Guix. It looks like README contains
dated instruction on how to install the project and it's missing some estimated
time for tests to be passed; sometimes unit tests timeout to pass after 168.030s+.

Thanks,
Oleg

**Comment by Stebalien** [comment]
I've removed the outdated information from the readme. In terms of the tests, we've tried to make them as timing independent as possible but can still flake occasionally. But I'm not going to document the time the unit tests take in the readme.
