### ISSUE TITLE
Use go-metrics-interface

### ISSUE THREAD

**Issue by Kubuxu** [libp2p/go-flow-metrics#5]
For compatibility with Prometheus.

**Comment by Stebalien** [comment]
If possible, I'd rather not complicate this library by adding new interfaces/deps. It's designed to be the fastest rate-tracking library available and that's it.

**Comment by Kubuxu** [comment]
For metrics interface, it just has to increase `Total` counter. It can even update it even N calls. 
The core reason for adding metrics interface is to have metrics in a standard location that is being scraped.

**Comment by Stebalien** [comment]
I'm not sure I follow. This library has per-meter total counters that are automatically maintained.

**Comment by Kubuxu** [comment]
Doesn't matter we can probably do it as adapter on top of this module.
